### ISSUE TITLE
Request for pretrained_models

### ISSUE THREAD

**Issue by emleeee** [ta012/MaxAST#1]
Hi, Tony Alex:

Thanks for your magnificent work on MaxAST! When I ran this repo, I noticed that the file at the path "../../pretrained_models/audioset_fullset/best_audio_model_maxast.pth" seems to be missing. Could you please re-upload this file? 

Thank you for taking the time to read my question. I look forward to your response！

**Comment by ta012** [comment]
Hi,

You can download the file from the link provided in the README and place it in the specified folder. For convenience, here’s the link:  
[Download File - Google Drive](https://drive.google.com/file/d/10qB6ByUooMLMGUv2B2nWEstpEs3fgTii/view)
